spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/big_project
spring.datasource.username=root
spring.datasource.password=rohan@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver